### ISSUE TITLE
mediaType & content aren't required here

### ISSUE THREAD

**Issue by KyleAMathews** [tumblbug/gatsby-source-workable#1]
https://github.com/tumblbug/gatsby-source-workable/blob/17cb421e25c1b2ba6deecf0f7bee43f03d083081/src/gatsby-node.js#L25

You only add them when indicating to transformer plugins that there is raw content that they can transform.

Otherwise this looks great!

**Comment by bjrnt** [comment]
Thank for you for the feedback! :) I've removed the unnecessary `mediaType`.
